--
server:
  name: YOUR_SERVER_CUSTOM_NAME
backup:
  server1: root@1.2.3.4
  server2: root@1.2.3.4
#  server3: root@1.2.3.4
s3:
  bucket1:
    access: 123
    secret: 456
    endpoint: fra1.digitaloceanspaces.com
#  bucket2:
#    access: 123
#    secret: 456
#    endpoint: fra1.digitaloceanspaces.com
#  bucket3:
#    access: 123
#    secret: 456
#    endpoint: fra1.digitaloceanspaces.com
